# Describes the format for MESH Panel services.
notify:
  description: "Sends a notification to a specific MESH panel."
  fields:
    title:
      description: "Title of the notification."
      example: "Hello"
    message:
      description: "Message of the notification."
      example: "World!"
    duration:
      description: "Duration of the notification in milliseconds."
      example: 5000